<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.8">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <title>Start</title>

</head>
<style>
    .img-container-block {
        text-align: center;
    }

    .img-container-inline {
        text-align: center;
        display: block;
    }

    .slide-in-bck-center {
        -webkit-animation: slide-in-bck-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940);
        animation: slide-in-bck-center 2s cubic-bezier(0.250, 0.460, 0.450, 0.940);
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-8-29 15:50:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation slide-in-bck-center
 * ----------------------------------------
 */
    @-webkit-keyframes slide-in-bck-center {
        0% {
            -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
            opacity: 0;
        }

        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }

    @keyframes slide-in-bck-center {
        0% {
            -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
            opacity: 0;
        }

        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }



    .centered {
        position: fixed;
        top: 50%;
        left: 50%;
        /* bring your own prefixes */
        transform: translate(-50%, -50%);
    }

    body {
        background-image: url('stars.gif');
    }


    .above {
        position: fixed;
        width: 500px;
        height: 600px;
        margin: -300px auto auto -250px;
        top: 50%;
        left: 50%;
        text-align: center;
    }

    .box {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        position: relative;
        padding: 20px 50px;
        display: inline-block;
        text-decoration: none;
        text-transform: uppercase;
        overflow: hidden;
        cursor: pointer;
        font: 16px/24px Arial, sans-serif;
        background-color: #4973ff;
        transition:
            box-shadow 0.4s ease,
            background-color 0.4s ease,
            color 0.4s ease;
        box-shadow:
            0 0 2px 0 rgba(73, 115, 255, .1),
            0 0 4px 0 rgba(73, 115, 255, .2),
            0 0 6px 0 rgba(73, 115, 255, .3),
            0 0 8px 0 rgba(73, 115, 255, .4),
            0 0 12px 0 rgba(73, 115, 255, .5),
            0 0 18px 0 rgba(73, 115, 255, .6);
    }

    .box:hover {
        background-color: #ea3c;
        box-shadow:
            0 0 2px 0 rgba(238, 170, 51, 0.1),
            0 0 4px 0 rgba(238, 170, 51, 0.2),
            0 0 6px 0 rgba(238, 170, 51, 0.3),
            0 0 8px 0 rgba(238, 170, 51, 0.4),
            0 0 12px 0 rgba(238, 170, 51, 0.5),
            0 0 18px 0 rgba(238, 170, 51, 0.6),
            0 0 4px 0 rgba(238, 170, 51, 0.7);
    }

    .box span {
        position: relative;
        z-index: 1;
        color: #fff;
        letter-spacing: 8px;
    }

    .box i {
        position: absolute;
        left: 0;
        top: 50%;
        transform: translateY(-50%);
        width: 100%;
        height: 200px;
        background-color: inherit;
        box-shadow: inset 0 0 50px rgba(0, 0, 0, 0.5);
        transition:
            transform 0.4s linear,
            top 1s linear;
        overflow: hidden;
    }

    .box i:before,
    .box i:after {
        content: "";
        position: absolute;
        width: 200%;
        height: 200%;
        top: 0;
        left: 50%;
        transform: translate(-50%, -75%);
    }

    .box i:before {
        border-radius: 46%;
        background-color: rgba(20, 20, 20, 0.2);
        animation: animate 5s linear infinite;
    }

    .box i:after {
        border-radius: 40%;
        background-color: rgba(20, 20, 20, 0.5);
        animation: animate 10s linear infinite;
    }

    @keyframes animate {
        0% {
            transform:
                translate(-50%, -75%) rotate(0deg);
        }

        100% {
            transform:
                translate(-50%, -75%) rotate(360deg);
        }
    }


    .div1 {
        width: 50%;
        height: 70px;
        margin: 0 auto;
    }

    .puff-in-center {
        -webkit-animation: puff-in-center 4s cubic-bezier(0.470, 0.000, 0.745, 0.715) reverse backwards;
        animation: puff-in-center 4s cubic-bezier(0.470, 0.000, 0.745, 0.715) reverse backwards;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-8-25 20:23:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation puff-in-center
 * ----------------------------------------
 */
    @-webkit-keyframes puff-in-center {
        0% {
            -webkit-transform: scale(2);
            transform: scale(2);
            -webkit-filter: blur(4px);
            filter: blur(4px);
            opacity: 0;
        }

        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }

    @keyframes puff-in-center {
        0% {
            -webkit-transform: scale(2);
            transform: scale(2);
            -webkit-filter: blur(4px);
            filter: blur(4px);
            opacity: 0;
        }

        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }

    @-webkit-keyframes loading {
        0% {
            width: 0;
        }

        100% {
            width: 100%;
        }
    }

    @keyframes loading {
        0% {
            width: 0;
        }

        100% {
            width: 100%;
        }
    }


    .loadingbar {
        display: -webkit-box;
        display: flex;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        height: 100%;
    }




    .four {
        position: absolute;
        top: 17%;
        left: 30%;
        width: 40%;
        display: -webkit-box;
        display: flex;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
    }

    footer {
        width: 100%;
        height: 600px;
        background-image: url(cartoonwave.gif);
        background-size: 100% 100%;
    }

    .scale-in-ver-bottom {
        -webkit-animation: scale-in-ver-bottom 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: scale-in-ver-bottom 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-8-29 16:57:19
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation scale-in-ver-bottom
 * ----------------------------------------
 */
    @-webkit-keyframes scale-in-ver-bottom {
        0% {
            -webkit-transform: scaleY(0);
            transform: scaleY(0);
            -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
            opacity: 1;
        }

        100% {
            -webkit-transform: scaleY(1);
            transform: scaleY(1);
            -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
            opacity: 1;
        }
    }

    @keyframes scale-in-ver-bottom {
        0% {
            -webkit-transform: scaleY(0);
            transform: scaleY(0);
            -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
            opacity: 1;
        }

        100% {
            -webkit-transform: scaleY(1);
            transform: scaleY(1);
            -webkit-transform-origin: 0% 100%;
            transform-origin: 0% 100%;
            opacity: 1;
        }
    }

    .manipulate {
        position: absolute;
        width: 300px;
        height: 500px;
        bottom: 0px;
        right: 25%;
        left: 50%;
        margin-left: -150px;
    }

    .manipulate2 {
        position: absolute;
        bottom: 0px;

    }

    /* ---------- Fog ---------- */
    .fogwrapper {
        height: 100%;
        position: absolute;
        top: 0;
        width: 100%;
        -webkit-filter: blur(1px) grayscale(0.2) saturate(1.2) sepia(0.2);
        filter: blur(1px) grayscale(0.2) saturate(1.2) sepia(0.2);
    }

    #foglayer_01,
    #foglayer_02,
    #foglayer_03 {
        height: 100%;
        position: absolute;
        width: 200%;
    }

    #foglayer_01 .image01,
    #foglayer_01 .image02,
    #foglayer_02 .image01,
    #foglayer_02 .image02,
    #foglayer_03 .image01,
    #foglayer_03 .image02 {
        float: left;
        height: 100%;
        width: 50%;
    }

    #foglayer_01 {
        -webkit-animation: foglayer_01_opacity 10s linear infinite, foglayer_moveme 15s linear infinite;
        -moz-animation: foglayer_01_opacity 10s linear infinite, foglayer_moveme 15s linear infinite;
        animation: foglayer_01_opacity 10s linear infinite, foglayer_moveme 15s linear infinite;
    }

    #foglayer_02,
    #foglayer_03 {
        -webkit-animation: foglayer_02_opacity 21s linear infinite, foglayer_moveme 13s linear infinite;
        -moz-animation: foglayer_02_opacity 21s linear infinite, foglayer_moveme 13s linear infinite;
        animation: foglayer_02_opacity 21s linear infinite, foglayer_moveme 13s linear infinite;
    }

    /* ---------- Moving Fog ---------- */
    /*
  'size: cover' || 'size: 100%'; results remain the same
  'attachment: scroll' can be added or removed; results remain the same
  'attachment: fixed' causing unexpected results in Chrome
  'repeat-x' || 'no-repeat'; results remain the same
*/
    #foglayer_01 .image01,
    #foglayer_01 .image02 {
        background: url("https://raw.githubusercontent.com/danielstuart14/CSS_FOG_ANIMATION/master/fog1.png") center center/cover no-repeat transparent;
    }

    #foglayer_02 .image01,
    #foglayer_02 .image02,
    #foglayer_03 .image01,
    #foglayer_03 .image02 {
        background: url("https://raw.githubusercontent.com/danielstuart14/CSS_FOG_ANIMATION/master/fog2.png") center center/cover no-repeat transparent;
    }

    /* ---------- Keyframe Layer 1 ---------- */
    @-webkit-keyframes foglayer_01_opacity {
        0% {
            opacity: .1;
        }

        22% {
            opacity: .5;
        }

        40% {
            opacity: .28;
        }

        58% {
            opacity: .4;
        }

        80% {
            opacity: .16;
        }

        100% {
            opacity: .1;
        }
    }

    @-moz-keyframes foglayer_01_opacity {
        0% {
            opacity: .1;
        }

        22% {
            opacity: .5;
        }

        40% {
            opacity: .28;
        }

        58% {
            opacity: .4;
        }

        80% {
            opacity: .16;
        }

        100% {
            opacity: .1;
        }
    }

    @-o-keyframes foglayer_01_opacity {
        0% {
            opacity: .1;
        }

        22% {
            opacity: .5;
        }

        40% {
            opacity: .28;
        }

        58% {
            opacity: .4;
        }

        80% {
            opacity: .16;
        }

        100% {
            opacity: .1;
        }
    }

    @keyframes foglayer_01_opacity {
        0% {
            opacity: .1;
        }

        22% {
            opacity: .5;
        }

        40% {
            opacity: .28;
        }

        58% {
            opacity: .4;
        }

        80% {
            opacity: .16;
        }

        100% {
            opacity: .1;
        }
    }

    /* ---------- Keyframe Layer 2 ---------- */
    @-webkit-keyframes foglayer_02_opacity {
        0% {
            opacity: .5;
        }

        25% {
            opacity: .2;
        }

        50% {
            opacity: .1;
        }

        80% {
            opacity: .3;
        }

        100% {
            opacity: .5;
        }
    }

    @-moz-keyframes foglayer_02_opacity {
        0% {
            opacity: .5;
        }

        25% {
            opacity: .2;
        }

        50% {
            opacity: .1;
        }

        80% {
            opacity: .3;
        }

        100% {
            opacity: .5;
        }
    }

    @-o-keyframes foglayer_02_opacity {
        0% {
            opacity: .5;
        }

        25% {
            opacity: .2;
        }

        50% {
            opacity: .1;
        }

        80% {
            opacity: .3;
        }

        100% {
            opacity: .5;
        }
    }

    @keyframes foglayer_02_opacity {
        0% {
            opacity: .5;
        }

        25% {
            opacity: .2;
        }

        50% {
            opacity: .1;
        }

        80% {
            opacity: .3;
        }

        100% {
            opacity: .5;
        }
    }

    /* ---------- Keyframe Layer 3 ---------- */
    @-webkit-keyframes foglayer_03_opacity {
        0% {
            opacity: .8
        }

        27% {
            opacity: .2;
        }

        52% {
            opacity: .6;
        }

        68% {
            opacity: .3;
        }

        100% {
            opacity: .8;
        }
    }

    @-moz-keyframes foglayer_03_opacity {
        0% {
            opacity: .8
        }

        27% {
            opacity: .2;
        }

        52% {
            opacity: .6;
        }

        68% {
            opacity: .3;
        }

        100% {
            opacity: .8;
        }
    }

    @-o-keyframes foglayer_03_opacity {
        0% {
            opacity: .8
        }

        27% {
            opacity: .2;
        }

        52% {
            opacity: .6;
        }

        68% {
            opacity: .3;
        }

        100% {
            opacity: .8;
        }
    }

    @keyframes foglayer_03_opacity {
        0% {
            opacity: .8;
        }

        27% {
            opacity: .2;
        }

        52% {
            opacity: .6;
        }

        68% {
            opacity: .3;
        }

        100% {
            opacity: .8;
        }
    }

    /* ---------- Keyframe moveMe ---------- */
    @-webkit-keyframes foglayer_moveme {
        0% {
            left: 0;
        }

        100% {
            left: -100%;
        }
    }

    @-moz-keyframes foglayer_moveme {
        0% {
            left: 0;
        }

        100% {
            left: -100%;
        }
    }

    @-o-keyframes foglayer_moveme {
        0% {
            left: 0;
        }

        100% {
            left: -100%;
        }
    }

    @keyframes foglayer_moveme {
        0% {
            left: 0;
        }

        100% {
            left: -100%;
        }
    }

    @media only screen and (min-width: 280px) and (max-width: 767px) {

        #foglayer_01 .image01,
        #foglayer_01 .image02,
        #foglayer_02 .image01,
        #foglayer_02 .image02,
        #foglayer_03 .image01,
        #foglayer_03 .image02 {
            width: 100%;
        }
    }

    html,
    body {
        margin: 0;
        height: 100%;
        overflow: hidden
    }

    .slide-out-top {
        -webkit-animation: slide-out-top 6.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
        animation: slide-out-top 6.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-9-1 20:33:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
    @-webkit-keyframes slide-out-top {
        0% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            opacity: 1;
        }

        100% {
            -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
            opacity: 0;
        }
    }

    @keyframes slide-out-top {
        0% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            opacity: 1;
        }

        100% {
            -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
            opacity: 0;
        }
    }

    .Text {
        font-size: 20px;
        animation: TextAnimation 10s infinite;
        opacity: 0.4;


    }


    @keyframes TextAnimation {
        0% {
            color: #fff;
        }

        50% {
            font-size: 35px;
        }

        100% {
            color: #fff;
        }
    }

    .hide {
        display: none;
    }

    .myDIV:hover+.hide {
        display: block;
        color: red;
    }

    @keyframes cssAnimation {
        to {
            width: 0;
            height: 0;
            overflow: hidden;
        }
    }

    @-webkit-keyframes cssAnimation {
        to {
            width: 0;
            height: 0;
            visibility: hidden;
        }
    }

    .loading {
        text-transform: uppercase;
        font-family: 'Cabin Condensed', sans-serif;
        font-weight: bold;
        font-size: 25px;
        text-align: center;
        height: 120px;
        line-height: 110px;
        vertical-align: bottom;
        position: absolute;
        left: 0;
        right: 0;
        top: 525px;
        bottom: 0;
        display: block;
    }

    @keyframes wave-animation {
        0% {
            background-position: 0 bottom;
        }

        100% {
            background-position: 200px bottom;
        }
    }

    @keyframes loading-animation {
        0% {
            background-size: 200px 0px;
        }

        100% {
            background-size: 200px 200px;
        }
    }

    .wave {
        background-image: url("waveloading.png");
        -moz-background-clip: text;
        -o-background-clip: text;
        -webkit-background-clip: text;
        background-clip: text;
        color: hsl(0, 0%, 100%, 0.4);
        text-shadow: 0px 0px rgba(255, 255, 255, 0.06);
        animation: wave-animation 1s infinite linear, loading-animation 10s infinite linear alternate;
        background-size: 200px 100px;
        background-repeat: repeat-x;
        opacity: 1;
    }

    .fade-in-bck {
        -webkit-animation: fade-in-bck 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) reverse both;
        animation: fade-in-bck 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) reverse both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-9-15 20:29:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation fade-in-bck
 * ----------------------------------------
 */
    @-webkit-keyframes fade-in-bck {
        0% {
            -webkit-transform: translateZ(80px);
            transform: translateZ(80px);
            opacity: 0;
        }

        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }

    @keyframes fade-in-bck {
        0% {
            -webkit-transform: translateZ(80px);
            transform: translateZ(80px);
            opacity: 0;
        }

        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }
</style>

<body>
    <div id="foglayer_01" class="fog">
        <div class="image01"></div>
        <div class="image02"></div>
    </div>
    <div id="foglayer_02" class="fog">
        <div class="image01"></div>
        <div class="image02"></div>
    </div>
    <div id="foglayer_03" class="fog">
        <div class="image01"></div>
        <div class="image02"></div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <!-- <img src="start.gif" onClick="alert('Click On Our Logo In Order To Access The Page'); " id="start"></img> -->

    <div id="image_holder" class="div1" style="display:none">


        <div class="one"></div>
        <div class="two"></div>
        <div class="three"></div>
        <div class="four">

            <div class="wrapper">
                <div class="bg">
                    <div class="el"></div>
                </div>
            </div>
        </div>



        <div class="centered" id="second">
            <p class="slide-out-top">
                <img src="logo.jpg" width="200" height="200" id="imgClickAndChange" onclick="changeImage()" />
            </p>
        </div>

        <!-- <div class="centered" id="second">
            <p class="scale-in-ver-bottom">
                <img alt="" src="logo.jpg" width="250" height="250" id="imgClickAndChange" onclick="changeImage()" />
            </p>
        </div> -->



    </div>

    <!-- <footer class="scale-in-ver-bottom" style="display:none" id="waves"></footer> -->
    </div>

    <div class="hide">
        <div class="div1" onclick="changeImage()" id="start">
            <div class="manipulate">
                <div class="box" id="startbutton">
                    <i></i>
                </div>
            </div>
        </div>
    </div>

    <div class="loading wave">
    <div id="animatedtext">
        Wavehouse Entertaiment
        </div>
    </div>



    <div class="centered" id="first">
        <p class="slide-in-bck-center">
            <img alt="" src="wavey.gif" width="200" height="200" id="imgClickAndChange" onclick="changeImage()" />
        </p>
    </div>

    <div class="centered" onclick="changeImage()" id="initialclick">
        <div class="Text">Click Me</div>

    </div>



</body>
<script>
    function changeImage() {

        if (document.getElementById("imgClickAndChange").src = "logo.jpg") {
            document.getElementById("imgClickAndChange").src = "wavey.gif";
            document.getElementById("image_holder").style.display = "flex";
            document.getElementById("startbutton").style.display = "none";
            // document.getElementById("waves").style.display = "flex";
            document.getElementById("initialclick").style.display = "none";

            document.getElementById("animatedtext").classList.add('fade-in-bck');
            document.getElementById("start").style.display = "none";
            document.getElementById("first").style.display = "none";

            window.setTimeout(function() {

                // Move to a new location or you can do something else
                window.location.href = "/start";
                document.getElementById("imgClickAndChange").style.display = "none";


            }, 3500);
        } else {
            document.getElementById("imgClickAndChange").src = "wave.gif";
        }

    }
</script>

</html>